// File generated by FlutterFire CLI.
//this file was generated by firebase to setup firebase
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKsU2LEqBwsYBauG3LQ_Is8HPnIWL7h7M',
    appId: '1:366690138320:web:6e07f4fcb7371ae0f4c6d5',
    messagingSenderId: '366690138320',
    projectId: 'ispell-43edc',
    authDomain: 'ispell-43edc.firebaseapp.com',
    storageBucket: 'ispell-43edc.appspot.com',
    measurementId: 'G-X8RXDNN4SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrgFy2U2tWUl1ls5lxNzFnCmCUbHm_vRE',
    appId: '1:366690138320:android:810bfbb045400ee3f4c6d5',
    messagingSenderId: '366690138320',
    projectId: 'ispell-43edc',
    storageBucket: 'ispell-43edc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Oj8G0jdUOfSLCym_FXe1vCDnMtwvfpw',
    appId: '1:366690138320:ios:7edf82e329bd9f73f4c6d5',
    messagingSenderId: '366690138320',
    projectId: 'ispell-43edc',
    storageBucket: 'ispell-43edc.appspot.com',
    androidClientId:
        '366690138320-hvvhuljuoqv6iupa3t0tkuu1qi9f6519.apps.googleusercontent.com',
    iosClientId:
        '366690138320-2vmfttfms9tqnot1iqbp7kjrns9h8uo4.apps.googleusercontent.com',
    iosBundleId:
        'com.example.englishTest.OneSignalNotificationServiceExtension',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2Oj8G0jdUOfSLCym_FXe1vCDnMtwvfpw',
    appId: '1:366690138320:ios:cef21864fdf57424f4c6d5',
    messagingSenderId: '366690138320',
    projectId: 'ispell-43edc',
    storageBucket: 'ispell-43edc.appspot.com',
    androidClientId:
        '366690138320-hvvhuljuoqv6iupa3t0tkuu1qi9f6519.apps.googleusercontent.com',
    iosClientId:
        '366690138320-l6kamagkpq3pm6gk132hli54506hc79a.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishTest',
  );
}
